# Generated by Django 3.2.12 on 2024-05-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20240502_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
    ]
